name: 'Setup BlakePorts Environment'
description: 'Sets up BlakePorts repository and MacPorts configuration'

runs:
  using: 'composite'
  steps:
    - name: Set up blakeports symlink and sync
      shell: bash
      run: |
        # Create ~/code directory if it doesn't exist
        mkdir -p ~/code
        
        # Create symlink if it doesn't exist
        if [ ! -e ~/code/blakeports ]; then
          echo "Creating symlink to blakeports..."
          ln -s "${{ github.workspace }}" ~/code/blakeports
        else
          echo "✓ BlakePorts already exists at ~/code/blakeports"
        fi
        
    - name: Check if MacPorts configuration needs updating
      shell: bash
      run: |
        # Set flag to determine if we need to sync
        NEED_SYNC=false
        
        # Check if MacPorts is installed by checking for the binary directly
        if [ ! -f /opt/local/bin/port ]; then
          echo "MacPorts not installed, running installmacports..."
          cd ~/code/blakeports
          sudo ./scripts/installmacports
          NEED_SYNC=true
        else
          echo "✓ MacPorts already installed"
          
          # Check if sources.conf has our configuration
          if ! grep -q "file:///Users/$(whoami)/code/blakeports" /opt/local/etc/macports/sources.conf 2>/dev/null; then
            echo "BlakePorts not configured in sources.conf, updating..."
            cd ~/code/blakeports
            
            # Add blakeports source before the rsync source  
            echo 'file:///Users/'"$(whoami)"'/code/blakeports [default]' | sudo tee /tmp/blakeports_source.conf > /dev/null
            sudo sed -i '' '/^rsync:\/\/rsync\.macports\.org/r /tmp/blakeports_source.conf' /opt/local/etc/macports/sources.conf
            sudo rm /tmp/blakeports_source.conf
            
            NEED_SYNC=true
          else
            echo "✓ BlakePorts already configured in sources.conf"
          fi
        fi
        
        # Export the flag for the next step
        echo "NEED_SYNC=$NEED_SYNC" >> $GITHUB_ENV
        
    - name: Update port index if needed
      shell: bash
      run: |
        # Source MacPorts environment from our local copy
        source ~/code/blakeports/setupenv.bash
        
        if [ "$NEED_SYNC" = "true" ]; then
          echo "Updating port index..."
          cd ~/code/blakeports
          sudo portindex
        else
          echo "✓ Port index sync not needed"
        fi 