#!/bin/bash
set -euo pipefail
IFS=$'\n\t'
shopt -s nullglob nocaseglob

# path to self and parent dir
SCRIPT=$(realpath $0)
SCRIPTPATH=$(dirname $SCRIPT)

# Variables with default values
VAULT_ADDR="${VAULT_ADDR:-https://vault.example.com:8200}"
VAULT_AGENT_ROLEID="${VAULT_AGENT_ROLEID:-}"
VAULT_AGENT_SECRETID="${VAULT_AGENT_SECRETID:-}"


# determine CPU architecture
ARCH=$(uname -m)
ARCH=${ARCH/x86_64/amd64}
ARCH=${ARCH/aarch64/arm64}

# get latest release version from github for macports
PORT_LATEST_RELEASE=$(curl -s https://api.github.com/repos/macports/macports-base/releases/latest | grep tag_name | cut -d '"' -f 4)
PORT_LATEST_RELEASE_NUMBER=${PORT_LATEST_RELEASE#v}

# get macOS operating system version long name including california parks using system_profiler
MACOS_VERSION=$(sw_vers --ProductVersion | cut -d . -f1)
MACOS_VERSION_NAME=$(awk '/SOFTWARE LICENSE AGREEMENT FOR macOS/' '/System/Library/CoreServices/Setup Assistant.app/Contents/Resources/en.lproj/OSXSoftwareLicense.rtf' | awk -F 'macOS ' '{print $NF}' | awk '{print substr($0, 0, length($0)-1)}')

# test for macports and install if not present
if ! command -v /opt/local/bin/port &>/dev/null; then
  echo "Installing macports..."
  MACOS_VERSION=$(sw_vers -productVersion | cut -f 1 -d .)
  if [[ $MACOS_VERSION -ge 26 ]]; then
    cd
    echo "macOS version $MACOS_VERSION is not supported by macports installer"
    echo "Attempting install from source..."
    curl -O https://distfiles.macports.org/MacPorts/MacPorts-${PORT_LATEST_RELEASE_NUMBER}.tar.bz2
    tar xf MacPorts-${PORT_LATEST_RELEASE_NUMBER}.tar.bz2
    cd MacPorts-${PORT_LATEST_RELEASE_NUMBER}/
    ./configure
    make
    sudo make install
    cd
    rm -rf MacPorts-${PORT_LATEST_RELEASE_NUMBER}*
  else
    MACPORTS_PKG="https://github.com/macports/macports-base/releases/download/${PORT_LATEST_RELEASE}/MacPorts-${PORT_LATEST_RELEASE_NUMBER}-${MACOS_VERSION}-${MACOS_VERSION_NAME}.pkg"
    echo $MACPORTS_PKG
    curl -s -L -o /tmp/macports.pkg $MACPORTS_PKG
    sudo installer -pkg /tmp/macports.pkg -target /
    rm /tmp/macports.pkg
  fi
fi

# configure macports sources

# configure macports archive sites

# configure macports.conf

# macports selfupdate after config
if [[ -e /opt/local/bin/port ]]; then
  sudo /opt/local/bin/port selfupdate
fi


exit 0