version: '3.8'

services:
  github-runner:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        # Override runner version if needed
        RUNNER_VERSION: ${RUNNER_VERSION:-2.321.0}
    container_name: ${RUNNER_NAME:-github-runner-1}
    hostname: ${RUNNER_NAME:-github-runner-1}
    restart: unless-stopped
    
    # Environment variables for runner configuration
    environment:
      - GITHUB_OWNER=${GITHUB_OWNER}
      - GITHUB_REPO=${GITHUB_REPO}
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - RUNNER_NAME=${RUNNER_NAME:-github-runner-1}
      - RUNNER_WORKDIR=${RUNNER_WORKDIR:-_work}
      - CUSTOM_LABELS=${CUSTOM_LABELS:-}
    
    # Volume mounts
    volumes:
      # Persist runner work directory
      - runner-work:/home/runner/_work
      
      # Mount SSH keys for VM access (read-only)
      - ${SSH_KEY_PATH:-~/.ssh}:/home/runner/.ssh:ro
      
      # Optional: Mount custom SSH config
      # - ./ssh_config:/home/runner/.ssh/config:ro
    
    # Network configuration
    network_mode: bridge
    
    # Resource limits (optional, adjust as needed)
    # deploy:
    #   resources:
    #     limits:
    #       cpus: '2'
    #       memory: 4G
    #     reservations:
    #       cpus: '1'
    #       memory: 2G

volumes:
  runner-work:
    driver: local

