name: Build netatalk4

on:
  push:
    paths:
      - 'net/netatalk4/**'
    branches: [main]
  pull_request:
    paths:
      - 'net/netatalk4/**'
    branches: [main]
  workflow_dispatch:

jobs:
  build-netatalk4:
    runs-on: [self-hosted, macOS, ARM64, tart]
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup BlakePorts Environment
      uses: ./.github/actions/setup-blakeports
        
    - name: Clean existing netatalk4 installation
      run: |
        # Set up MacPorts PATH explicitly
        export PATH="/opt/local/bin:/opt/local/sbin:$PATH"
        
        # Uninstall and clean if port already exists
        if port installed netatalk4 | grep -q netatalk4; then
          echo "Removing existing netatalk4 installation..."
          sudo port -f uninstall netatalk4
          sudo port clean netatalk4
        else
          echo "No existing netatalk4 installation found"
        fi
        
    - name: Build netatalk4 port
      run: |
        # Set up MacPorts PATH explicitly
        export PATH="/opt/local/bin:/opt/local/sbin:$PATH"
        
        sudo port -v install netatalk4
        
    - name: Verify netatalk4 installation
      run: |
        # Set up MacPorts PATH explicitly
        export PATH="/opt/local/bin:/opt/local/sbin:$PATH"
        
        port installed netatalk4
        which afpd || echo "afpd binary not found in PATH"
        ls -la /opt/local/sbin/afpd || echo "afpd binary not found" 