name: Build nrsc5 (Simple)

on:
  push:
    paths:
      - 'audio/nrsc5/**'
    branches: [main]
  pull_request:
    paths:
      - 'audio/nrsc5/**'
    branches: [main]
  workflow_dispatch:

jobs:
  build-nrsc5:
    runs-on: [self-hosted, macOS, ARM64, tart]
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        path: blakeports
        
    - name: Update BlakePorts index
      run: |
        # Copy updated files to the configured BlakePorts directory
        rsync -av --delete blakeports/ /Users/admin/code/blakeports/
        cd /Users/admin/code/blakeports
        sudo portindex
        
    - name: Build nrsc5 port
      run: sudo port -v install nrsc5
        
    - name: Verify nrsc5 installation
      run: |
        port installed nrsc5
        which nrsc5 || echo "nrsc5 binary not found in PATH" 