name: Build Ports Matrix

on:
  push:
    paths:
      - 'audio/nrsc5/**'
      - 'devel/libcbor/**'
      - 'security/libfido2/**'
      - 'net/netatalk4/**'
    branches: [main]
  pull_request:
    paths:
      - 'audio/nrsc5/**'
      - 'devel/libcbor/**'
      - 'security/libfido2/**'
      - 'net/netatalk4/**'
    branches: [main]
  workflow_dispatch:
    inputs:
      ports:
        description: 'Comma-separated list of ports to build (e.g., nrsc5,libcbor)'
        required: false
        default: 'nrsc5,libcbor,libfido2,netatalk4'

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      ports: ${{ steps.changes.outputs.ports }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
          
      - id: changes
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "ports=[\"$(echo '${{ inputs.ports }}' | sed 's/,/","/g')\"]" >> $GITHUB_OUTPUT
          else
            changed_files=$(git diff --name-only HEAD~1 HEAD)
            ports=()
            if echo "$changed_files" | grep -q "^audio/nrsc5/"; then
              ports+=("nrsc5")
            fi
            if echo "$changed_files" | grep -q "^devel/libcbor/"; then
              ports+=("libcbor")
            fi
            if echo "$changed_files" | grep -q "^security/libfido2/"; then
              ports+=("libfido2")
            fi
            if echo "$changed_files" | grep -q "^net/netatalk4/"; then
              ports+=("netatalk4")
            fi
            
            if [ ${#ports[@]} -eq 0 ]; then
              echo "ports=[]" >> $GITHUB_OUTPUT
            else
              printf -v joined '"%s",' "${ports[@]}"
              echo "ports=[${joined%,}]" >> $GITHUB_OUTPUT
            fi
          fi

  build-ports:
    needs: detect-changes
    if: needs.detect-changes.outputs.ports != '[]'
    runs-on: [self-hosted, macOS, ARM64, tart]
    strategy:
      matrix:
        port: ${{ fromJson(needs.detect-changes.outputs.ports) }}
      fail-fast: false
      
    steps:
    - name: Setup BlakePorts Environment
      uses: ./.github/actions/setup-blakeports
      
    - name: Build ${{ matrix.port }} port
      run: |
        sudo port -v install ${{ matrix.port }}
        
    - name: Verify ${{ matrix.port }} installation
      run: |
        port installed ${{ matrix.port }} 