name: Build netatalk4

on:
  push:
    paths:
      - 'net/netatalk4/**'
    branches: [main]
  pull_request:
    paths:
      - 'net/netatalk4/**'
    branches: [main]
  workflow_dispatch:

jobs:
  build-netatalk4:
    name: build-netatalk4 (${{ matrix.runner }})
    strategy:
      matrix:
        runner: [macOS_15, macOS_26_Beta]
      fail-fast: false
    runs-on: ${{ matrix.runner }}
    
    steps:
    - name: Show macOS version
      run: |
        echo "Running on: ${{ matrix.runner }}"
        sw_vers
        
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup MacPorts and BlakePorts Environment
      run: |
        cd ~/code/blakeports
        ./scripts/installmacports
        
    - name: Install dependencies
      run: |
        cd ~/code/blakeports
        ./scripts/install-deps netatalk4
        
    - name: Clean existing netatalk4 installation
      run: |
        # Source MacPorts environment from our local copy
        source ~/code/blakeports/setupenv.bash
        
        # Uninstall and clean if port already exists
        if port installed netatalk4 | grep -q netatalk4; then
          echo "Removing existing netatalk4 installation..."
          sudo port -f uninstall netatalk4
          sudo port clean netatalk4
        else
          echo "No existing netatalk4 installation found"
        fi
        
    - name: Build netatalk4 port
      run: |
        # Source MacPorts environment from our local copy
        source ~/code/blakeports/setupenv.bash
        
        sudo port -v install netatalk4
        
    - name: Verify netatalk4 installation
      run: |
        # Source MacPorts environment from our local copy
        source ~/code/blakeports/setupenv.bash
        
        port installed netatalk4
        which afpd || echo "afpd binary not found in PATH"
        ls -la /opt/local/sbin/afpd || echo "afpd binary not found" 