name: Build libcbor

on:
  push:
    paths:
      - 'devel/libcbor/**'
    branches: [main]
  pull_request:
    paths:
      - 'devel/libcbor/**'
    branches: [main]
  workflow_dispatch:

jobs:
  build-libcbor:
    runs-on: [self-hosted, macOS, ARM64, tart]
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup BlakePorts Environment
      uses: ./.github/actions/setup-blakeports
        
    - name: Clean existing libcbor installation
      run: |
        # Uninstall and clean if port already exists
        if port installed libcbor | grep -q libcbor; then
          echo "Removing existing libcbor installation..."
          sudo port -f uninstall libcbor
          sudo port clean libcbor
        else
          echo "No existing libcbor installation found"
        fi
        
    - name: Build libcbor port
      run: |
        sudo port -v install libcbor
        
    - name: Verify libcbor installation
      run: |
        port installed libcbor
        ls -la /opt/local/lib/libcbor* || echo "libcbor libraries not found" 