name: Build bstring (Legacy macOS)

on:
  push:
    paths:
      - 'textproc/bstring/**'
    branches: [main]
  pull_request:
    paths:
      - 'textproc/bstring/**'
    branches: [main]
  workflow_dispatch:
    inputs:
      vm_ip:
        description: 'Override TenSeven VM IP (optional, uses TENSEVEN_IP var if not provided)'
        required: false
        type: string
      macos_version:
        description: 'macOS version to test (tenseven, snowleopard, mountainlion)'
        required: false
        type: choice
        default: 'tenseven'
        options:
          - tenseven
          - snowleopard
          - mountainlion
          - mavericks
          - yosemite

env:
  # Default to TenSeven VM for now (only one configured)
  VM_IP: ${{ inputs.vm_ip || vars.TENSEVEN_IP }}
  VM_USERNAME: ${{ vars.TENSEVEN_USERNAME }}

jobs:
  build-bstring-tenseven:
    name: Build bstring on Mac OS X 10.7 (TenSeven)
    runs-on: [self-hosted, docker, ssh-capable]
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Verify VM configuration
      run: |
        if [ -z "$VM_IP" ]; then
          echo "Error: VM_IP not set. Provide vm_ip input or set TENSEVEN_IP repository variable."
          exit 1
        fi
        if [ -z "$VM_USERNAME" ]; then
          echo "Error: VM_USERNAME not set. Set TENSEVEN_USERNAME repository variable."
          exit 1
        fi
        echo "Will connect to: $VM_USERNAME@$VM_IP"
    
    - name: Show macOS version on TenSeven VM
      uses: appleboy/ssh-action@v1
      with:
        host: ${{ env.VM_IP }}
        username: ${{ env.VM_USERNAME }}
        key: ${{ secrets.TENSEVEN_KEY }}
        script: |
          echo "=================================================="
          echo "  Building bstring on Mac OS X 10.7 (TenSeven)"
          echo "=================================================="
          sw_vers
          echo ""
          uname -a
    
    - name: Prepare repository on TenSeven VM
      uses: appleboy/ssh-action@v1
      with:
        host: ${{ env.VM_IP }}
        username: ${{ env.VM_USERNAME }}
        key: ${{ secrets.TENSEVEN_KEY }}
        script: |
          echo "Preparing blakeports repository..."
          
          # Clone or update repository
          if [ -d ~/blakeports-ci/.git ]; then
            echo "Repository exists, updating..."
            cd ~/blakeports-ci
            git fetch origin
            git reset --hard origin/main
            git clean -fdx
          else
            echo "Cloning repository..."
            git clone https://github.com/trodemaster/blakeports.git ~/blakeports-ci
            cd ~/blakeports-ci
          fi
          
          echo "Current commit: $(git rev-parse --short HEAD)"
          echo "✅ Repository ready"
    
    - name: Setup MacPorts and BlakePorts Environment
      uses: appleboy/ssh-action@v1
      with:
        host: ${{ env.VM_IP }}
        username: ${{ env.VM_USERNAME }}
        key: ${{ secrets.TENSEVEN_KEY }}
        command_timeout: 30m
        script: |
          cd ~/blakeports-ci
          
          echo "Setting up MacPorts environment..."
          ./scripts/installmacports
          
          echo "✅ MacPorts setup complete"
    
    - name: Lint portfile
      uses: appleboy/ssh-action@v1
      with:
        host: ${{ env.VM_IP }}
        username: ${{ env.VM_USERNAME }}
        key: ${{ secrets.TENSEVEN_KEY }}
        script: |
          cd ~/blakeports-ci
          source ./setupenv.bash
          
          echo "Linting textproc/bstring portfile..."
          port lint --nitpick textproc/bstring
          
          echo "✅ Lint passed"
    
    - name: Clean existing bstring installation
      uses: appleboy/ssh-action@v1
      with:
        host: ${{ env.VM_IP }}
        username: ${{ env.VM_USERNAME }}
        key: ${{ secrets.TENSEVEN_KEY }}
        script: |
          cd ~/blakeports-ci
          source ./setupenv.bash
          
          echo "Cleaning existing bstring installation..."
          sudo port -f uninstall bstring || true
          sudo port clean --dist bstring
          
          echo "✅ Clean complete"
    
    - name: Install dependencies
      uses: appleboy/ssh-action@v1
      with:
        host: ${{ env.VM_IP }}
        username: ${{ env.VM_USERNAME }}
        key: ${{ secrets.TENSEVEN_KEY }}
        command_timeout: 30m
        script: |
          cd ~/blakeports-ci
          
          echo "Installing bstring dependencies..."
          ./scripts/install-deps bstring
          
          echo "✅ Dependencies installed"
    
    - name: Build bstring port
      uses: appleboy/ssh-action@v1
      with:
        host: ${{ env.VM_IP }}
        username: ${{ env.VM_USERNAME }}
        key: ${{ secrets.TENSEVEN_KEY }}
        command_timeout: 30m
        script: |
          cd ~/blakeports-ci
          source ./setupenv.bash
          
          echo "Building bstring port..."
          sudo port -v install bstring
          
          echo "✅ Build complete"
    
    - name: Verify bstring installation
      uses: appleboy/ssh-action@v1
      with:
        host: ${{ env.VM_IP }}
        username: ${{ env.VM_USERNAME }}
        key: ${{ secrets.TENSEVEN_KEY }}
        script: |
          cd ~/blakeports-ci
          source ./setupenv.bash
          
          echo "Verifying bstring installation..."
          port installed bstring
          
          echo "✅ Installation verified"
    
    - name: Test bstring with tests variant
      uses: appleboy/ssh-action@v1
      with:
        host: ${{ env.VM_IP }}
        username: ${{ env.VM_USERNAME }}
        key: ${{ secrets.TENSEVEN_KEY }}
        command_timeout: 30m
        script: |
          cd ~/blakeports-ci
          source ./setupenv.bash
          
          echo "Testing bstring with tests variant..."
          sudo port -v install bstring +tests
          
          echo "✅ Tests variant passed"
    
    - name: Cleanup
      if: always()
      uses: appleboy/ssh-action@v1
      with:
        host: ${{ env.VM_IP }}
        username: ${{ env.VM_USERNAME }}
        key: ${{ secrets.TENSEVEN_KEY }}
        script: |
          echo "Cleaning up CI directory..."
          rm -rf ~/blakeports-ci
          echo "✅ Cleanup complete"

