name: Build libcbor

on:
  push:
    paths:
      - 'devel/libcbor/**'
    branches: [main]
  pull_request:
    paths:
      - 'devel/libcbor/**'
    branches: [main]
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  build-libcbor:
    name: build-libcbor (${{ matrix.runner }})
    strategy:
      matrix:
        runner: [macOS_15, macOS_26_Beta]
      fail-fast: false
    runs-on: ${{ matrix.runner }}
    
    steps:
    - name: Show macOS version
      run: |
        echo "Running on: ${{ matrix.runner }}"
        sw_vers
        
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup MacPorts and BlakePorts Environment
      run: |
        ./scripts/installmacports
        
    - name: Install dependencies
      run: |
        ./scripts/install-deps libcbor
        
    - name: Clean existing libcbor installation
      run: |
        # Source MacPorts environment from our local copy
        source ./setupenv.bash
        
        # Uninstall and clean if port already exists
        if port installed libcbor | grep -q libcbor; then
          echo "Removing existing libcbor installation..."
          sudo port -f uninstall libcbor libfido2
          sudo port clean --dist libcbor libfido2
        else
          echo "No existing libcbor installation found"
        fi
        
    - name: Build libcbor port
      run: |
        # Source MacPorts environment from our local copy
        source ./setupenv.bash
        
        sudo port -v install libcbor
        
    - name: Verify libcbor installation
      run: |
        # Source MacPorts environment from our local copy
        source ./setupenv.bash
        
        port installed libcbor
        ls -la /opt/local/lib/libcbor* || echo "libcbor libraries not found" 