name: Hello TenSeven VM

on:
  workflow_dispatch:
    inputs:
      vm_ip:
        description: 'IP address of the TenSeven VM (must be running)'
        required: true
        type: string
      message:
        description: 'Custom message to display on VM'
        required: false
        default: 'Hello from GitHub Actions Docker Runner!'

jobs:
  # SSH into the running VM and say hello
  hello-vm:
    runs-on: [self-hosted, docker, ssh-capable]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Say Hello to TenSeven VM
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ inputs.vm_ip }}
          username: ${{ secrets.TENSEVEN_USERNAME }}
          key: ${{ secrets.TENSEVEN_KEY }}
          script: |
            echo "=================================================="
            echo "  ${{ github.event.inputs.message }}"
            echo "=================================================="
            echo ""
            echo "System Information:"
            echo "------------------"
            uname -a
            echo ""
            echo "Hostname:"
            echo "---------"
            hostname
            echo ""
            echo "macOS Version:"
            echo "--------------"
            sw_vers
            echo ""
            echo "Uptime:"
            echo "-------"
            uptime
            echo ""
            echo "Current User:"
            echo "-------------"
            whoami
            echo ""
            echo "Current Date/Time:"
            echo "------------------"
            date
            echo ""
            echo "Disk Space:"
            echo "-----------"
            df -h / | tail -1
            echo ""
            echo "Memory Usage:"
            echo "-------------"
            vm_stat | head -5
            echo ""
            echo "=================================================="
            echo "  Hello World from Mac OS X 10.7 Lion!"
            echo "  Connected via Docker Runner with OpenSSH 9.x"
            echo "=================================================="

