name: Install MacPorts

on:
  push:
    paths:
      - 'scripts/installmacports'
    branches: [main]
  pull_request:
    paths:
      - 'scripts/installmacports'
    branches: [main]
  workflow_dispatch:

jobs:
  install-macports:
    name: install-macports (${{ matrix.runner }})
    strategy:
      matrix:
        runner: [macOS_15, macOS_26_Beta]
      fail-fast: false
    runs-on: ${{ matrix.runner }}
    
    steps:
    - name: Show macOS version
      run: |
        echo "Running on: ${{ matrix.runner }}"
        sw_vers
        
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup BlakePorts Environment
      uses: ./.github/actions/setup-blakeports
      
    - name: Verify MacPorts installation
      run: |
        # Source MacPorts environment from our local copy
        source ~/code/blakeports/setupenv.bash
        
        echo "Checking MacPorts installation..."
        /opt/local/bin/port version || echo "MacPorts not found in expected location"
        which port || echo "port command not in PATH"
        echo "Checking blakeports configuration..."
        grep "file:///" /opt/local/etc/macports/sources.conf || echo "BlakePorts source not found" 