name: Install MacPorts

on:
  push:
    paths:
      - 'scripts/installmacports'
    branches: [main]
  pull_request:
    paths:
      - 'scripts/installmacports'
    branches: [main]
  workflow_dispatch:

jobs:
  install-macports:
    runs-on: [self-hosted, macOS, ARM64, tart]
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup BlakePorts Environment
      uses: ./.github/actions/setup-blakeports
      
    - name: Verify MacPorts installation
      run: |
        # Set up MacPorts PATH explicitly
        export PATH="/opt/local/bin:/opt/local/sbin:$PATH"
        
        echo "Checking MacPorts installation..."
        /opt/local/bin/port version || echo "MacPorts not found in expected location"
        which port || echo "port command not in PATH"
        echo "Checking blakeports configuration..."
        grep "file:///" /opt/local/etc/macports/sources.conf || echo "BlakePorts source not found" 