name: VMware VM Start - TenSeven

on:
  workflow_dispatch:
    inputs:
      vm_name:
        description: 'Start the 10.7 VM'
        required: true
        default: 'tenseven-test'

jobs:
  start-vm:
    runs-on: [self-hosted, ubuntu, noble]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Start VMware VM
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HYPERVISOR_HOST }}
          username: ${{ secrets.HYPERVISOR_USERNAME }}
          key: ${{ secrets.HYPERVISOR_KEY }}
          debug: true
          script: |
            export VMW_SOURCE_VM_PATH="/Volumes/JonesFarm/actions-runners/Mac OS X 10.7.vmwarevm"
            export VMW_VM_PATH="/Volumes/JonesFarm/actions-runners/tenseven-runner.vmwarevm"
            export VMW_VM_NAME="tenseven-runner"
            
            echo Source VM Path: "$VMW_SOURCE_VM_PATH"
            echo VM Path: "$VMW_VM_PATH"
            echo VM Name: "$VMW_VM_NAME"
            
            which vmrun
