name: VMware VM Start - TenSeven

on:
  workflow_dispatch:
    inputs:
      vm_name:
        description: 'Start the 10.7 VM'
        required: true
        default: 'tenseven-test'

jobs:
  start-vm:
    runs-on: [self-hosted, ubuntu, noble]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Start VMware VM
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HYPERVISOR_HOST }}
          username: ${{ secrets.HYPERVISOR_USERNAME }}
          key: ${{ secrets.HYPERVISOR_KEY }}
          debug: true
          script: |
            export VMW_SOURCE_VM_PATH="/Volumes/JonesFarm/actions-runners/Mac OS X 10.7.vmwarevm/Mac OS X 10.7.vmx"
            export VMW_VM_PATH="/Volumes/JonesFarm/actions-runners/tenseven-runner.vmwarevm/tenseven-runner.vmx"
            export VMW_VM_NAME="tenseven-runner"
            VMRUN="/Applications/VMware Fusion.app/Contents/Public/vmrun"
            echo Source VM Path: "$VMW_SOURCE_VM_PATH"
            echo VM Path: "$VMW_VM_PATH"
            echo VM Name: "$VMW_VM_NAME"
            
            # List current VMs
            echo "Current VMs:"
            "$VMRUN" -T fusion list
            
            # Create linked clone from source VM
            echo "Creating linked clone..."
            "$VMRUN" -T fusion clone "$VMW_SOURCE_VM_PATH" "$VMW_VM_PATH" linked -cloneName="$VMW_VM_NAME"
            
            # Start the cloned VM
            echo "Starting cloned VM..."
            "$VMRUN" -T fusion start "$VMW_VM_PATH"
            
            # Verify VM is running
            echo "Running VMs after start:"
            "$VMRUN" -T fusion list
